apiVersion: v1
data:
  MONGO_PASSWORD: {{ printf .Values.mongo.user | b64enc | quote }}
  MONGO_USERNAME: {{ printf .Values.mongo.password | b64enc | quote }}
kind: Secret
metadata:
  name: mongodb-backup-login
type: Opaque
