apiVersion: v1
data:
  mongodump-all-db.sh: |-
    #!/bin/bash

        mongodump -h $MONGO_HOST -u $MONGO_USERNAME -p $MONGO_PASSWORD -o $BACKUPS_FOLDER --forceTableScan --gzip --authenticationDatabase admin
kind: ConfigMap
metadata:
  name: mongodb-backup-all-db-sh